"""Optional authenticated FastAPI adapter for the local pipeline runtime."""

from axcalib.api.app import create_app
from axcalib.api.artifacts import (
    ArtifactPurpose,
    RejectAllStagedArtifactResolver,
    StagedArtifactResolver,
)
from axcalib.api.auth import (
    ApiPipelineGrant,
    ApiPrincipal,
    ApiRole,
    RejectAllTokenVerifier,
    TokenVerifier,
)
from axcalib.api.models import (
    CancelRunResponse,
    CompletionDecisionRequest,
    EducationCommandResponse,
    EducationCompletionDecisionRequest,
    EducationEnrollmentCreateRequest,
    EducationEnrollmentView,
    EducationManualConfirmationRequest,
    EducationProgramView,
    EducationProjectBindRequest,
    EducationRevisionRequest,
    EducationScoreRequest,
    PipelineCatalogResponse,
    PipelineRunRequest,
    PipelineRunView,
    Problem,
    ProjectCommandResponse,
    ProjectRegistrationRequest,
    ProjectRegistrationResponse,
    RegistrationDecisionRequest,
    StagedArtifactRef,
)

__all__ = [
    "ApiPipelineGrant",
    "ApiPrincipal",
    "ApiRole",
    "ArtifactPurpose",
    "CancelRunResponse",
    "CompletionDecisionRequest",
    "EducationCommandResponse",
    "EducationCompletionDecisionRequest",
    "EducationEnrollmentCreateRequest",
    "EducationEnrollmentView",
    "EducationManualConfirmationRequest",
    "EducationProgramView",
    "EducationProjectBindRequest",
    "EducationRevisionRequest",
    "EducationScoreRequest",
    "PipelineCatalogResponse",
    "PipelineRunRequest",
    "PipelineRunView",
    "Problem",
    "ProjectCommandResponse",
    "ProjectRegistrationRequest",
    "ProjectRegistrationResponse",
    "RegistrationDecisionRequest",
    "RejectAllStagedArtifactResolver",
    "RejectAllTokenVerifier",
    "TokenVerifier",
    "StagedArtifactRef",
    "StagedArtifactResolver",
    "create_app",
]
